openapi: 3.0.0
info:
  version: 1.0.0
  title: Jobs API
servers:
  - url: "https://jobs-api-tydg.onrender.com/api/v1"
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Williams Balogun
                email: williamsbalogun49@gmail.com
                password: secret
            examples:
              default:
                value:
                  name: Williams Balogun
                  email: williamsbalogun49@gmail.com
                  password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
  /auth/login:
    post:
      tags:
        - auth
      summary: login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: williamsbalogun49@gmail.com
                password: secret
            examples:
              default:
                value:
                  email: williamsbalogun49@gmail.com
                  password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
  /jobs:
    get:
      tags:
        - jobs
      summary: Get all jobs
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security:
        - bearerAuth: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
    post:
      tags:
        - jobs
      summary: create job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: afren ai
                position: Software Engineer
            examples:
              default:
                value:
                  company: afren ai
                  position: Software Engineer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security:
        - bearerAuth: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
  "/jobs/{job_id}":
    get:
      tags:
        - jobs
      summary: get job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security:
        - bearerAuth: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
    patch:
      tags:
        - jobs
      summary: update job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                position: Google developer
            examples:
              default:
                value:
                  position: Google developer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security:
        - bearerAuth: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
    delete:
      tags:
        - jobs
      summary: remove job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      security:
        - bearerAuth: []
      servers:
        - url: "https://jobs-api-tydg.onrender.com/api/v1"
tags:
  - name: auth
  - name: jobs
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
